### ISSUE TITLE
[Roadmap] SITreg using the SAP Cloud Application Programming Model

### ISSUE THREAD

**Issue by gregorwolf** [sapmentors/sitregcapm#1]
- [x] Project setup
- [x] Invite contributors
- [x] Add get started to readme
- [ ] Build admin service containing all entities including tests and business logic
- [ ]  Implement organizer service with business logic and tests
- [x] Add authentication
- [ ] Implement participant service with business logic and tests
- [ ] Implement public service with business logic and tests
- [ ] Implement receptionist service with business logic and tests
